# Taskfile for webserver related tasks
# # E.g. created droplet, deploying website, etc.
version: "3"

includes:
  droplet:
    taskfile: taskfile-droplet.yml
    flatten: false

tasks:
  new-slideshow:
    desc: "Create a new reveal.js presentation in current directory. Optionally provide SUBDIR to specify a subdirectory."
    vars:
      SUBDIR: '{{default "" .SUBDIR}}'
    prerequisites:
      - test -d "{{.TASKFILE_DIR}}/revealjs-template"
    cmds:
      - echo "Creating new reveal.js presentation in {{.USER_WORKING_DIR}}/{{.SUBDIR}}"
      - scripts/new-revealjs.sh "{{.TASKFILE_DIR}}/revealjs-template" "{{.USER_WORKING_DIR}}" "{{.SUBDIR}}"

  new-static-site:
    desc: "Initialize a new static site on the webserver droplet (requires SITE_NAME, optional DOMAIN to create a new caddy config from template)"
    requires:
      vars: [SSH_NAME, SITE_NAME]
    vars:
      SSH_NAME: '{{default "webserver" .SSH_NAME}}'
      DOMAIN: '{{default "" .DOMAIN}}'
    cmds:
      - |
        echo "Initializing new static site on droplet {{.SSH_NAME}}:sites/{{.SITE_NAME}}"
      - scripts/setup-webserver-new-static-site.sh "{{.SSH_NAME}}" "{{.SITE_NAME}}" "{{.DOMAIN}}"

  remove-site:
    desc: "Remove a site from the webserver droplet (requires SITE_NAME)"
    prompt: 'Are you sure you want to remove site ''{{.SITE_NAME}}'' from the server "{{.SSH_NAME}}?"'
    requires:
      vars: [SSH_NAME, SITE_NAME]
    cmds:
      - scripts/remove-webserver-site.sh "{{.SSH_NAME}}" "{{.SITE_NAME}}"

  deploy-static:
    desc: "Deploy website (static files) to droplet (requires STATIC_DIR and SITE_NAME)"
    requires:
      vars: [SSH_NAME, SITE_NAME]
    vars:
      SSH_NAME: '{{default "webserver" .SSH_NAME}}'
      STATIC_DIR: '{{default "static" .STATIC_DIR}}'
      ROOT_DIR: "{{default .USER_WORKING_DIR .ROOT_DIR}}"
      _FULL_DIR: "{{.ROOT_DIR}}/{{.STATIC_DIR}}/"
    preconditions:
      - sh: test -d "{{._FULL_DIR}}"
        msg: |
          Directory "{{._FULL_DIR}}" does not exist (maybe need to change the STATIC_DIR variable? 
          (or run from different dir or explicitly set ROOT_DIR))
    cmds:
      - |
        echo "Deploying static files from {{._FULL_DIR}} to server at {{.SSH_NAME}}:srv/www/{{.SITE_NAME}}"
      # First copy to the webserver user directory
      - rsync -avz --delete {{._FULL_DIR}}/ {{.SSH_NAME}}:sites/{{.SITE_NAME}}/static/
      - task: caddy-reload
        vars:
          SSH_NAME: "{{.SSH_NAME}}"

  caddy-reload:
    desc: "Reload the Caddy webserver after sending any configuration changes"
    requires:
      vars: [SSH_NAME]
    vars:
      SSH_NAME: '{{default "webserver" .SSH_NAME}}'
    cmds:
      - scripts/send-webserver-config.sh "{{.SSH_NAME}}"
      - ssh {{.SSH_NAME}} < scripts/webserver-update-static-files.sh
      # Do a quick caddy reload (sufficient for minor changes) (or start if no services running)
      # NOTE: May require logging into container repos first via `echo $GH_PAT | docker login -u <username> ghcr.io --password-stdin`
      - ssh {{.SSH_NAME}} "docker exec caddy caddy reload --config /etc/caddy/Caddyfile || docker compose -f caddy-compose.yaml up -d"
      - task: _caddy-restart-compose-if-changed
        vars:
          SSH_NAME: "{{.SSH_NAME}}"

  _caddy-restart-compose-if-changed:
    silent: true
    internal: true
    desc: "Fully restarts the docker compose services if the compose file has changed (locally)"
    requires:
      vars: [SSH_NAME]
    sources:
      - caddy-compose.yaml
    cmds:
      # Fully stop and start in case any changes made to compose file
      - ssh {{.SSH_NAME}} "docker compose -f caddy-compose.yaml down && docker compose -f caddy-compose.yaml up -d"
