name: Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: read

    steps:
      # NOTE: if the action fails to set up python or R environments correctly, you should be able to do that here before calling the action.
      # E.g., Make sure QUARTO_PYTHON points to a python with jupyter, pandas, plotly, etc. installed.

      - name: Deploy site via template action
        uses: TimChild/webserver-template/actions/deploy-quarto-static-site@main
        with:
          vps-ip: ${{ vars.VPS_IP }}
          site-name: ${{ vars.SITE_NAME }}
          uses-python: true
          uses-r: false
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-user: "webadmin"
