name: Deploy Reflex Site

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "DOMAIN=${{ vars.DOMAIN }}" > .env
          echo "RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}" >> .env
          echo "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}" >> .env

      - name: Deploy frontend
        uses: TimChild/webserver-template/actions/deploy-reflex-frontend@main
        with:
          vps-ip: ${{ vars.VPS_IP }}
          site-name: ${{ vars.SITE_NAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove .env
        if: always()
        run: rm .env

  deploy-backend:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env for backend
        run: |
          echo "DOMAIN=${{ vars.DOMAIN }}" >> .env
          echo "RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}" >> .env
          echo "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}" >> .env

      - name: Deploy backend
        uses: TimChild/webserver-template/actions/deploy-reflex-backend@main
        permissions:
          packages: write
        with:
          vps-ip: ${{ vars.DROPLET_IP }}
          site-name: ${{ vars.SITE_NAME }}
          dotenv-path: .env
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove .env
        if: always()
        run: rm .env
